In [1]:
import pandas as pd

In [37]:
f = pd.read_csv(r'C:\Users\palejparra\Falabella\EQUIPO-ANALYTICS - General\DATA\F3\220725_f3.csv', sep=';', dtype='object')

In [33]:
ss = pd.read_excel('f3_sin_soporte.xlsx', dtype=str)

In [54]:
res = f.loc[ f['nro_devolucion'].isin(ss['Nro Devolucion'])].reset_index(drop=True)

In [59]:
tienda = ['101', '108', '93', '6', '183', '25', '38', '53', '13', '43', '82', '138', '72', '35', '60', '123', 
'98', '36', '19', '18', '50', '45', '85', '56', '96', '322', '131', '139', '141', '143', '5', '142', '37', '30']

cd = ['9951', '9921', '3000', '9903', '2000', '2001',
      '2002', '9970', '9901', '3002', '9905', '9961']

In [60]:
res.local[0]

'101'

In [61]:
res.loc[res.local.isin(tienda), 'local_agg'] = 'TIENDA'
res.loc[res.local.isin(cd), 'local_agg'] = 'CD'
res.loc[res.local_agg.isna(), 'local_agg'] = 'OTROS'

In [62]:
res.groupby('local_agg').count()

,nro_devolucion,fecha_reserva,fecha_envio,fecha_anulacion,fecha_confirmacion,nro_guia,tipo_producto,upc,sku,descripcion,...,cantidad,cant*costo,cant*costoprmd,diferencia,cant*precio,tipo_documento_para_dev,usuario_que_confirma,nc_proveedor,folio_f11,folio_f12
local_agg,,,,,,,,,,,,,,,,,,,,,
CD,134,134,134,0,0,134,134,134,134,134,...,134,134,134,134,134,134,0,0,0,77
TIENDA,1283,1283,1281,1,2,1281,1283,1283,1283,1283,...,1283,1283,1283,1276,1283,1283,1,1,0,90

In [63]:
res.to_excel('220727_f3_producto_sin_soporte.xlsx', index=False)

In [38]:
f.head()

,nro_devolucion,fecha_reserva,fecha_envio,fecha_anulacion,fecha_confirmacion,nro_guia,tipo_producto,upc,sku,descripcion,...,cantidad,cant*costo,cant*costoprmd,diferencia,cant*precio,tipo_documento_para_dev,usuario_que_confirma,nc_proveedor,folio_f11,folio_f12
0,32780000,06-mar-2021,06-mar-2021,14-may-2021,NaN,215505,producto,2003487790004,3487790,led 32 recco hd smt rec-le3219ns(d),...,1,389849,389849,0,599000,nota credito,ljgomez,nce588,118371054,NaN
1,32850000,15-abr-2021,15-abr-2021,23-ago-2021,NaN,221379,market place,2004281237009,4281237,botin negro viola 603 p,...,1,79900,79900,0,79900,nota credito,fparra,NaN,NaN,12636878700
2,32920000,18-may-2021,27-may-2021,27-jul-2021,NaN,228153,producto,50036338523,3389628,audifonos jbl t110bt blanco(d),...,1,56660,71284,14624,189900,nota credito,ljgomez,6647,1110787782,NaN
3,33080000,10-sep-2021,10-sep-2021,29-dic-2021,NaN,241135,producto,2004236606003,4236606,ec-swatch dreamwhite,...,1,251696,251696,0,769000,nota credito,lbeltran,10866,1111075819,NaN
4,33150000,23-oct-2021,23-oct-2021,29-dic-2021,NaN,248548,producto,840023208546,8206889,fusion 128 verde,...,1,713567,706279,7287,1499900,nota credito,lbeltran,6277519243,1111035318,NaN

In [26]:
f.loc[(f['CESTADO']==2) &( f['CTIPO']==4) & f.duplicated(['CTECH_KEY', 'PRD_UPC'], keep=False)].to_excel('f4dupc.xlsx')

In [9]:
f['TOTAL_COSTO'].sum()

13610338771

In [10]:
f.columns

Index(['f0_', 'KEY', 'CTECH_KEY', 'PRD_LVL_CHILD', 'PRD_UPC', 'QF04_SHIP',
       'MF04_UNIT_CST', 'TOTAL_COSTO', 'CESTADO', 'DESCESTADO', 'USR_REGISTRO',
       'FECHA_REGISTRO', 'USR_RESERVA', 'FECHA_RESERVA', 'USR_ENVIO',
       'FECHA_ENVIO', 'USR_ANULADO', 'FECHA_ANULADO', 'PROD_CAT_ID',
       'PROD_CAT_DESC', 'PROD_NAME', 'PROD_BRAND_ID', 'LOC_ID', 'LOC_NAME',
       'LOCAL_AGG', 'CTIPO', 'DESCTIPO', 'CCENT_COSTO_F', 'XDESTINO', 'TNOTAS',
       'COPERARIO', 'NFORMULARIO', 'BMARGEN'],
      dtype='object')